version: '3.8'
services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: bitnami/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_SPI_THEME_STATIC_MAX_AGE=-1
      - KC_SPI_THEME_CACHE_THEMES=false
    depends_on:
      - postgresql
    ports:
      - "8083:8080"
  
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis'

  celery:
    build: .
    command: celery -A e_commerce_backend worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key_here
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

  celery-beat:
    build: .
    command: celery -A e_commerce_backend beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key_here
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local