# Generated by Django 5.1.5 on 2025-02-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status_orderitem_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
